name: Cypress E2E Tests

on:
  push:
    branches: [ master ]

jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run Cypress tests (headless)
        run: npm run test:e2e:headless
        working-directory: frontend
        env:
          CYPRESS_baseUrl: ${{ github.event.client_payload.url }}
